=== Sergio-EsSo/MARK_2526T3/XML/Ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="titulo" type="xs:string"/>
<xs:element name="autor" type="xs:string"/>
<xs:element name="anio" type="xs:integer"/>
<xs:element name="genero">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ficcion" />
            <xs:enumeration value="Distopia" />
            <xs:enumeration value="Fantasia" />
            <xs:enumeration value="Romance" />
            <xs:enumeration value="Terror" />
        </xs:restriction>
    </xs:simpleType>
</xs:element>

<xs:element name="libro">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="titulo" />
            <xs:element ref="autor" />
            <xs:element ref="anio" />
            <xs:element ref="genero" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="libreria">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="libro" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== Sergio-EsSo/MARK_2526T3/XML/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="Ejercicio1.xsd">
    <libro>
        <titulo>El Gran Gatsby</titulo>
        <autor>F. Scott Fitzgerald</autor>
        <anio>1925</anio>
        <genero>Ficcion</genero>
    </libro>
    <libro>
        <titulo>1984</titulo>
        <autor>George Orwell</autor>
        <anio>1949</anio>
        <genero>Distopia</genero>
    </libro>
    <libro>
        <titulo>Cien años de soledad</titulo>
        <autor>Gabriel García Márquez</autor>
        <anio>1967</anio>
        <genero>Ficcion</genero>
    </libro>
    <libro>
        <titulo>El Hobbit</titulo>
        <autor>J.R.R. Tolkien</autor>
        <anio>1937</anio>
        <genero>Fantasia</genero>
    </libro>
    <libro>
        <titulo>Drácula</titulo>
        <autor>Bram Stoker</autor>
        <anio>1897</anio>
        <genero>Terror</genero>
    </libro>
    <libro>
        <titulo>Orgullo y Prejuicio</titulo>
        <autor>Jane Austen</autor>
        <anio>1813</anio>
        <genero>Romance</genero>
    </libro>
    <libro>
        <titulo>Fahrenheit 451</titulo>
        <autor>Ray Bradbury</autor>
        <anio>1953</anio>
        <genero>Distopia</genero>
    </libro>
    <libro>
        <titulo>Crónica de una muerte anunciada</titulo>
        <autor>Gabriel García Márquez</autor>
        <anio>1981</anio>
        <genero>Ficcion</genero>
    </libro>
    <libro>
        <titulo>El resplandor</titulo>
        <autor>Stephen King</autor>
        <anio>1977</anio>
        <genero>Terror</genero>
    </libro>
    <libro>
        <titulo>Harry Potter y la piedra filosofal</titulo>
        <autor>J.K. Rowling</autor>
        <anio>1997</anio>
        <genero>Fantasia</genero>
    </libro>
    <libro>
        <titulo>Un mundo feliz</titulo>
        <autor>Aldous Huxley</autor>
        <anio>1932</anio>
        <genero>Distopia</genero>
    </libro>
    <libro>
        <titulo>El amor en los tiempos del cólera</titulo>
        <autor>Gabriel García Márquez</autor>
        <anio>1985</anio>
        <genero>Romance</genero>
    </libro>
    <libro>
        <titulo>It</titulo>
        <autor>Stephen King</autor>
        <anio>1986</anio>
        <genero>Terror</genero>
    </libro>
    <libro>
        <titulo>El nombre de la rosa</titulo>
        <autor>Umberto Eco</autor>
        <anio>1980</anio>
        <genero>Ficcion</genero>
    </libro>
    <libro>
        <titulo>Los juegos del hambre</titulo>
        <autor>Suzanne Collins</autor>
        <anio>2008</anio>
        <genero>Distopia</genero>
    </libro>
    <libro>
        <titulo>Cumbres Borrascosas</titulo>
        <autor>Emily Brontë</autor>
        <anio>1847</anio>
        <genero>Romance</genero>
    </libro>
</libreria>
