=== Sergio-EsSo/MARK_2526T3/XML/lenguajes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="nombre" type="xs:string"/>
<xs:element name="creador" type="xs:string"/>
<xs:element name="annoCreacion" type="xs:gYear"/>


<xs:element name="lenguaje">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="nombre"/>
            <xs:element ref="creador"/>
            <xs:element ref="annoCreacion"/>
            <xs:choice>
                <xs:element name="descripcion" type="xs:string"/>
                <xs:element name="enlace_web" type="xs:anyURI"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="lenguajes">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="lenguaje" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== Sergio-EsSo/MARK_2526T3/XML/lenguajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<lenguajes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="lenguajes.xsd">
    <lenguaje>
        <nombre>Python</nombre>
        <creador>Guido van Rossum</creador>
        <annoCreacion>1991</annoCreacion>
        <descripcion>Pythons is a high-level, interpreted, and general-purpose 
            programming language that emphasizes readability with its notable use
            of significant whitespace.
        </descripcion>
    </lenguaje>
    <lenguaje>
        <nombre>Java</nombre>
        <creador>James Gosling</creador>
        <annoCreacion>1995</annoCreacion>
        <descripcion>Java is a class-based, object-oriented programming language that is
            designed to have as few implementation dependencies as possible
        </descripcion>
    </lenguaje>
    <lenguaje>
        <nombre>C++</nombre>
        <creador>Bjarne Stroustrup</creador>
        <annoCreacion>1985</annoCreacion>
        <descripcion>C++ is a general-purpose programming language created as an extension of the C
            programming language, or 'C with Classes'
        </descripcion>
    </lenguaje>
    <lenguaje>
        <nombre>JavaScript</nombre>
        <creador>Brendan Eich</creador>
        <annoCreacion>1995</annoCreacion>
        <enlace_web>https://developer.mozilla.org/es/docs/Web/JavaScript</enlace_web>
    </lenguaje>
    <lenguaje>
        <nombre>Ruby</nombre>
        <creador>Yukihiro Matsumoto</creador>
        <annoCreacion>1995</annoCreacion>
        <descripcion>Ruby is an interpreted, high-level, general-purpose programming language with a focus on simplicity and productivity.</descripcion>
    </lenguaje>
    <lenguaje>
        <nombre>Rust</nombre>
        <creador>Graydon Hoare</creador>
        <annoCreacion>2010</annoCreacion>
        <enlace_web>https://www.rust-lang.org/</enlace_web>
    </lenguaje>
    <lenguaje>
        <nombre>Go</nombre>
        <creador>Robert Griesemer, Rob Pike, and Ken Thompson</creador>
        <annoCreacion>2009</annoCreacion>
        <descripcion>Go is a statically typed, compiled programming language designed at Google for simplicity and efficiency.</descripcion>
    </lenguaje>
    <lenguaje>
        <nombre>Swift</nombre>
        <creador>Chris Lattner (Apple Inc.)</creador>
        <annoCreacion>2014</annoCreacion>
        <enlace_web>https://developer.apple.com/swift/</enlace_web>
    </lenguaje>
    <lenguaje>
        <nombre>PHP</nombre>
        <creador>Rasmus Lerdorf</creador>
        <annoCreacion>1994</annoCreacion>
        <descripcion>PHP is a general-purpose scripting language geared towards web development, originally standing for Personal Home Page.</descripcion>
    </lenguaje>
    <lenguaje>
        <nombre>Kotlin</nombre>
        <creador>JetBrains</creador>
        <annoCreacion>2011</annoCreacion>
        <enlace_web>https://kotlinlang.org/</enlace_web>
    </lenguaje>
</lenguajes>
