=== Sergio-EsSo/MARK_2526T3/XML/mayorista.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="operaciones">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="operacion" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="operacion">
    <xs:complexType>
        <xs:sequence>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:element ref="venta" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element ref="compra" maxOccurs="unbounded" minOccurs="0"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="venta">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="titulo" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="cantidad" type="xs:integer" maxOccurs="unbounded"/>
            <xs:element name="entregado" type="xs:boolean" minOccurs="0"/>
            <xs:element ref="importe"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="compra">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="titulo" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="proveedor" type="xs:string"/>
            <xs:element ref="fecha_compra"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="importe">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="moneda" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:element name="fecha_compra">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="dia" type="xs:integer"/>
            <xs:element name="mes" type="xs:integer"/>
            <xs:element name="año" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== Sergio-EsSo/MARK_2526T3/XML/mayorista1.xml
<?xml version="1.0" encoding="UTF-8"?>
<operaciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="mayorista.xsd">

<operacion>
    <compra>
        <titulo>La Biblia</titulo>
        <titulo>Pentateuco</titulo>
        <proveedor>Francisco Juan Editoriales</proveedor>
        <fecha_compra>
            <dia>19</dia>
            <mes>11</mes>
            <año>2025</año>
        </fecha_compra>
    </compra>
</operacion>

<operacion>
    <compra>
        <titulo>Diario de Marisa Velazquez</titulo>
        <proveedor>El rincón de Germán</proveedor>
        <fecha_compra>
            <dia>3</dia>
            <mes>1</mes>
            <año>2026</año>
        </fecha_compra>
    </compra>
    <venta>
        <titulo>50 Sombras de Grey</titulo>
        <cantidad>20</cantidad>
        <entregado>true</entregado>
        <importe moneda="euros">878.3</importe>
    </venta>
</operacion>

</operaciones>

=== Sergio-EsSo/MARK_2526T3/XML/mayorista2.xml
<?xml version="1.0" encoding="UTF-8"?>
<operaciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="mayorista.xsd">

<operacion>
    <venta>
        <titulo>100 Días de Soledad</titulo>
        <cantidad>35</cantidad>
        <entregado>false</entregado>
        <importe moneda="libras">723.42</importe>
    </venta>
</operacion>

<operacion>
    <venta>
        <titulo>Asesinato a Dos Velas</titulo>
        <cantidad>30</cantidad>
        <entregado>true</entregado>
        <importe moneda="euros">659.9</importe>
    </venta>
    <compra>
        <titulo>Diario de Marisa Velazquez</titulo>
        <proveedor>Editorial Margarita</proveedor>
        <fecha_compra>
            <dia>8</dia>
            <mes>2</mes>
            <año>2026</año>
        </fecha_compra>
    </compra>
</operacion>

<operacion>
    <venta>
        <titulo>Guia para un Psicopata</titulo>
        <cantidad>17</cantidad>
        <entregado>false</entregado>
        <importe moneda="dolares">245.67</importe>
    </venta>
    <venta>
        <titulo>Un Emprendedor en Nueva Delhi</titulo>
        <cantidad>5</cantidad>
        <entregado>false</entregado>
        <importe moneda="dolares zimbauenses">38250.4</importe>
    </venta>
</operacion>

</operaciones>
